@startuml gabbie

' Enum for Status
enum OrderStatus {
Pending
Processed
Delivered
}

enum Role {
Admin, 
Driver
}

enum DeliveryStatus {
Scheduled
InTransit
Completed
}

enum RouteStatus {
Optimizing
Completed
Failed
}

enum VehicleStatus {
Available
InUse
Maintenance
Unavailable
}

' BaseEntity, extended by every other class
abstract class BaseEntity {
+id: int
+createdAt: Date
+updatedAt: Date
}

' User entity
class User {
+username: string
-password: Password
+email: string
+role: Role
}


' Value Object: Password
class Password {
-hashedValue: string
+hash(rawPassword: string): Password
+verify(rawPassword: string): bool
+getHashedValue(): string
}

' Product entity
class Product {
+price: double
+weight: double
+name: string
+description: string
+stockQuantity: int
+imageUrl: string
}

' Address Value Object
class Address {
+country: string
+city: string
+zipcode: string
+street: string
}

' Location Value Object (for geographical coordinates)
class Location {
+latitude: double
+longitude: double
+address: Address
+name: string
}

' Order entity
class Order {
+totalAmount: double
+deliveryDate: Date
+deliveryAddress: Address
+phoneNumber: string
+items: List<OrderItem>
+status: OrderStatus
+note: string
}

' Route entity
class Route {
+totalDuration: int
+totalDistance: double
+optimized: bool
+startTime: Date
+endTime: Date
+waypoints: List<Location>
+status: RouteStatus
}

' Delivery entity
class Delivery {
+status: DeliveryStatus
+routeId: int
+vehicleId: int
+orderList: List<Order>
+deliveryTimeWindow: TimeWindow
+trackingId: string
}

' Vehicle entity
class Vehicle {
+licensePlate: string
+capacity: double
+status: VehicleStatus
+reserveStock: List<OrderItem>

}

class OrderItem {
+product: Product
+quantity: int
}

' Container as a Record 
class Container {
    type: string
    depositAmount: double
}

skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}


' Relations between entities
BaseEntity <|-- User
BaseEntity <|-- Product
BaseEntity <|-- Order
BaseEntity <|-- Delivery
BaseEntity <|-- Route
BaseEntity <|-- Vehicle

Order "1" *-- "*" Product : contains
Delivery "1" *-- "*" Order : delivers
Route "1" *-- "*" Location : contains
Vehicle "1" *-- "1" Delivery : delivers
Order "1" *-- "1" Address : has
Delivery "1" *-- "1" Route : associated with
Location "1" *-- "1" Address : has
Order "1" *-- "*" OrderItem : contains
@enduml
